language: go

go:
  - tip

env:
  global:
    - "PATH=/home/travis/gopath/bin:$PATH"
    - FRONTEND_VERSION="2018-03-15-16-18-27"

script:
  - curl -o build-prod.tar.gz -L "https://github.com/entwico/helm-deployer-fe/releases/download/${FRONTEND_VERSION}/dist.tar.gz"
  - tar xzf build-prod.tar.gz
  - make vendor generate test build dist