language: go

go:
  - tip

env:
  global:
    - "PATH=/home/travis/gopath/bin:$PATH"
    - FRONTEND_VERSION="0.1.0"

script:
  #- curl -o build-prod.tar.gz -L "https://github.com/entwico/helm-deployer-frontend/releases/download/v${FRONTEND_VERSION}/build-prod.tar.gz"
  #- tar xzf build-prod.tar.gz
  - make vendor generate test build dist